//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_cliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int Id { get; set; }
        public string text { get; set; }
        public int userId { get; set; }
        public int userId1 { get; set; }
    
        public virtual user user_sender { get; set; }
        public virtual user user_receiver { get; set; }
    }
}
